from final_year_project_django.ingestion import binning_expirment, text_aggrogation_object, gpt_3_summary
from final_year_project_django.search import find_similar_by_model_transformer

text_input = '''


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer elit metus, dapibus vitae turpis eget, sollicitudin aliquet mauris. Maecenas eu risus nulla. Fusce maximus risus eget tellus imperdiet aliquam. Vestibulum congue ex nec mauris laoreet, vel sodales elit congue. Morbi volutpat mi eu ligula euismod, non semper arcu tincidunt. Etiam gravida erat tortor, sed vestibulum dolor porta ac. Nulla dictum ante vel luctus tristique. Fusce eu lectus vel elit rutrum ultrices a vulputate magna. Donec vehicula scelerisque ex.

Maecenas blandit commodo lectus, eget congue est facilisis sed. Duis maximus lobortis metus, quis malesuada leo pulvinar ac. Maecenas porttitor finibus volutpat. Cras mattis vel nibh et suscipit. Quisque enim leo, viverra quis porttitor et, finibus eu justo. Nulla ultrices metus a vestibulum consectetur. Sed pharetra malesuada turpis, ac sollicitudin sapien rutrum eu. Quisque sit amet luctus enim. Aliquam urna orci, porttitor sed iaculis tincidunt, auctor ac magna. Suspendisse tristique tincidunt finibus. Phasellus id ullamcorper ipsum. Sed suscipit velit nisi, ac pharetra quam ultrices iaculis. Donec rutrum, massa at malesuada cursus, massa orci ultricies ligula, sed accumsan lectus magna non lacus.

Fusce at mattis massa. Nullam a lobortis justo, in vestibulum felis. Sed congue eros eu lectus posuere facilisis. Nullam a orci enim. Praesent pulvinar dictum nisi ut pellentesque. Nulla dapibus placerat turpis vel bibendum. Ut fermentum tempor maximus. Duis ultrices sem ultricies tempus consequat. Praesent efficitur, mauris a ullamcorper tincidunt, diam quam congue turpis, tristique consequat sapien leo a magna. Nunc eu velit mollis, iaculis erat ac, tempor ante.

Quisque aliquet leo sit amet tempus mattis. Donec vel mi vitae risus laoreet eleifend et et nisi. Sed sed ligula ac justo feugiat volutpat. Aliquam vehicula, leo id laoreet maximus, ipsum libero tincidunt nunc, at faucibus purus leo quis tellus. Duis elementum nunc augue, at varius sapien interdum ut. Sed tempus eleifend magna. Sed porta suscipit sem ut consequat. Nam orci magna, varius vel bibendum non, bibendum id metus. Sed facilisis ornare risus, ut aliquam erat tristique a. Aliquam neque tortor, finibus eget velit vitae, sagittis imperdiet mi. Ut sit amet risus sed mi convallis pretium. Donec tincidunt risus metus, id aliquet quam dictum non. Etiam quis turpis a nunc venenatis dictum. Cras rutrum, magna in lobortis consectetur, nibh quam ornare erat, a efficitur nulla ex non massa. Fusce a posuere tellus. Sed at porta dui.

Donec egestas, velit non euismod eleifend, sem nunc maximus dolor, ut vehicula erat metus scelerisque orci. Nunc sit amet velit gravida enim aliquet fringilla in at leo. Integer egestas tempus nunc sit amet eleifend. Proin pretium commodo bibendum. Nunc ante orci, bibendum quis sollicitudin a, scelerisque fermentum neque. Sed facilisis lectus sed tincidunt lacinia. Pellentesque a porta turpis. Fusce convallis vehicula nisl, suscipit convallis augue. Praesent scelerisque rhoncus metus et ullamcorper. Nullam sagittis, quam vitae consectetur molestie, dui velit rutrum ipsum, nec vestibulum libero felis a arcu. Mauris ipsum nisi, eleifend nec felis at, vestibulum bibendum quam. Nulla in dui in libero eleifend posuere.

Etiam vitae purus metus. Duis aliquam quis odio vel auctor. Nam euismod metus in sollicitudin ullamcorper. Donec iaculis tempor turpis, ut gravida nulla aliquam aliquam. Suspendisse potenti. Cras viverra porta augue ac laoreet. Duis porta justo a dolor porta, ut rhoncus nibh blandit. Sed lacinia, urna a sollicitudin pellentesque, magna purus lobortis orci, egestas dapibus quam felis tristique eros.

Maecenas ac risus sollicitudin, vestibulum orci vitae, pulvinar lorem. Donec tempor, odio id fermentum consequat, augue augue suscipit justo, id placerat justo lorem vel risus. Quisque ac volutpat risus. Aenean in turpis felis. Maecenas ultricies consectetur purus et pretium. Sed pretium egestas lacus, vel iaculis nisl luctus vel. Nunc dictum urna eget augue consectetur, eu aliquet erat venenatis. Cras lorem velit, blandit id semper ut, egestas nec lorem. Cras ex nunc, congue at placerat pulvinar, rutrum sit amet urna. Phasellus scelerisque interdum ipsum ac posuere. Phasellus ornare pharetra risus et volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi lobortis, ligula id pellentesque varius, arcu libero placerat nibh, at tincidunt metus tortor nec metus. Cras sagittis enim erat, et pretium libero tincidunt ac. Nullam vehicula mauris a felis fermentum congue. Curabitur pretium libero sit amet ornare varius.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In consequat diam quis justo auctor, id interdum est sollicitudin. In eu eros at sapien vestibulum maximus vitae at tellus. Donec facilisis velit ante, vel porttitor turpis lacinia sit amet. Etiam id tempus nisl. Integer bibendum nisl id metus bibendum, eu eleifend turpis venenatis. Integer mattis at augue et interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc tincidunt vitae felis in efficitur. Vestibulum sodales tellus sit amet erat mattis semper. Vestibulum viverra nulla nec nulla tincidunt elementum. Etiam fringilla accumsan tortor sit amet fringilla. In hac habitasse platea dictumst. Curabitur sagittis ante pharetra lectus venenatis varius. Nam felis ligula, volutpat id volutpat quis, vehicula eget mauris.

Maecenas a pretium augue. Curabitur sed felis lacinia, egestas sem sit amet, commodo ipsum. Mauris risus libero, porttitor sit amet risus sit amet, fringilla egestas orci. Aliquam eget ligula tempor, commodo sapien nec, maximus eros. Aenean mattis quis tortor eget mollis. Proin bibendum, eros id volutpat gravida, arcu dui vestibulum est, eu luctus ante mauris eu ante. Proin bibendum ullamcorper felis. Cras at aliquam orci, et ullamcorper tellus. Integer feugiat lobortis lacus, eget congue felis tempus vitae. Vivamus bibendum in ex vel ultrices. Suspendisse potenti. Fusce venenatis bibendum gravida. Fusce venenatis, elit eu vehicula congue, eros dui semper lectus, vel semper nisl urna quis tellus. Integer viverra ipsum nec lorem varius, in viverra odio molestie. Praesent at lorem quis quam posuere vulputate vel vitae leo. Curabitur mollis orci urna, in vulputate tellus finibus sed.

Duis vitae vehicula odio, condimentum scelerisque est. Praesent ex augue, venenatis quis tellus ac, congue commodo eros. Nullam enim urna, ultrices sed lacus at, tempus euismod dolor. Nullam ut semper odio, non euismod nunc. Aliquam nisi nisl, commodo condimentum ante a, sollicitudin rhoncus nibh. Sed tempor dignissim enim, non rutrum sapien convallis ut. Mauris vel purus ac tellus ornare faucibus ac id mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut sed tincidunt ante. In at euismod nunc. 
'''

def test_eval_binning():

    search_results = find_similar_by_model_transformer("France")
    summary = gpt_3_summary(text_aggrogation_object(search_results), use_bin=True)

    print(summary)
