# Generated by Django 3.2.12 on 2022-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_source', models.CharField(max_length=50)),
                ('tile', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('body_tldr', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
