# Generated by Django 3.2.12 on 2022-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_year_project_django', '0002_rename_tile_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
